"""Project a preserved SQLite snapshot into a fresh Friday-schema research candidate.

This is NOT a deployment or a complete semantic migration. Newer-only fields remain
in a full source-evidence snapshot; callers must resolve every workflow difference
before considering the candidate usable. Existing paths are never overwritten.
"""
from __future__ import annotations

import argparse
from collections import Counter
from contextlib import closing
from datetime import datetime, timezone
import hashlib
import json
from pathlib import Path
import sqlite3
from typing import Any

TARGET_REVISION = '20260910_0033'
SCHEMA_TABLES = frozenset({'alembic_version', 'alembic_schema_state'})


def _physical(path: Path) -> Path:
    """Refuse aliases so an output cannot point back into an input directory."""
    absolute = path.absolute()
    for entry in (absolute, *absolute.parents):
        if entry.is_symlink() or (hasattr(entry, 'is_junction') and entry.is_junction()):
            raise ValueError(f'linked paths are not allowed: {entry}')
    return absolute.resolve()


def _sha(path: Path) -> str:
    """Hash bytes without loading an entire database into memory."""
    with path.open('rb') as stream:
        return hashlib.file_digest(stream, 'sha256').hexdigest()


def _quoted(name: str) -> str:
    """Quote schema-owned SQLite identifiers, never interpolating SQL values."""
    return '"' + name.replace('"', '""') + '"'


def _read_only(path: Path) -> sqlite3.Connection:
    """Read a checkpointed offline snapshot without creating input sidecar files.

An active/WAL-dependent database is not a supported input. Its online backup must
be completed first; immutable mode must never silently ignore committed WAL data.
"""
    for suffix in ('-wal', '-journal'):
        sidecar = Path(str(path) + suffix)
        if sidecar.exists() and sidecar.stat().st_size:
            raise ValueError('input must be a checkpointed offline snapshot')
    connection = sqlite3.connect(path.as_uri() + '?mode=ro&immutable=1', uri=True)
    connection.execute('PRAGMA query_only=ON')
    connection.execute('BEGIN')
    return connection


def _shapes(connection: sqlite3.Connection) -> dict[str, list[str]]:
    """Return ordinary table columns; SQLite sequences are generated by inserts."""
    tables = connection.execute(
        "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name"
    ).fetchall()
    return {name: [row[1] for row in connection.execute(f'PRAGMA table_info({_quoted(name)})')]
            for name, in tables}


def _rows(connection: sqlite3.Connection, table: str, columns: list[str]) -> list[tuple]:
    """Read an explicit projection so newer-only fields are never silently mapped."""
    projection = ','.join(_quoted(column) for column in columns)
    return connection.execute(f'SELECT {projection} FROM {_quoted(table)}').fetchall()


def _row_hashes(rows: list[tuple]) -> Counter:
    """Compare full row multisets including duplicates, without emitting values."""
    def blob(value: Any) -> dict[str, str]:
        if isinstance(value, bytes):
            return {'sqlite_blob_hex': value.hex()}
        raise TypeError(f'Unsupported SQLite value type: {type(value).__name__}')
    return Counter(hashlib.sha256(json.dumps(row, ensure_ascii=False, separators=(',', ':'),
                                             default=blob).encode('utf-8')).hexdigest() for row in rows)


def _assert_integrity(connection: sqlite3.Connection) -> None:
    """Reject broken files and all foreign-key violations before publication."""
    if connection.execute('PRAGMA integrity_check').fetchall() != [('ok',)]:
        raise ValueError('SQLite integrity check failed')
    violations = connection.execute('PRAGMA foreign_key_check').fetchall()
    if violations:
        counts = dict(Counter(row[0] for row in violations))
        raise ValueError(f'foreign key check failed: {len(violations)} violation(s), tables={counts}')


def build_candidate(
    source_path: Path,
    template_path: Path,
    output_directory: Path,
    *,
    expected_source_sha256: str,
    expected_template_sha256: str,
) -> dict[str, Any]:
    """Copy current business state into a new old-schema DB, retaining full evidence.

    Only the newly created output directory is writable. Schema/version checkpoint
    rows come from a real canonical Friday bootstrap, not a stamp on the modern DB.
    No transaction is replayed, no repair is run, and no operation version is changed.
    """
    source_path, template_path, output_directory = map(
        _physical, (source_path, template_path, output_directory)
    )
    if output_directory.exists():
        raise ValueError('output directory already exists')
    if source_path == template_path:
        raise ValueError('source and schema template must be different files')
    source_hash = _sha(source_path)
    if source_hash != expected_source_sha256.lower():
        raise ValueError('source hash does not match the verified snapshot')
    template_hash = _sha(template_path)
    if template_hash != expected_template_sha256.lower():
        raise ValueError('template hash does not match the trusted schema template')
    with closing(_read_only(source_path)) as source, closing(_read_only(template_path)) as template:
        _assert_integrity(source)
        _assert_integrity(template)
        if template.execute('SELECT version_num FROM alembic_version').fetchall() != [(TARGET_REVISION,)]:
            raise ValueError('template revision must be the canonical Friday revision')
        source_shapes, target_shapes = _shapes(source), _shapes(template)
        business_tables = sorted(set(target_shapes) - SCHEMA_TABLES)
        for table in business_tables:
            if table not in source_shapes:
                raise ValueError(f'missing source table: {table}')
            missing = set(target_shapes[table]) - set(source_shapes[table])
            if missing:
                raise ValueError(f'missing source column: {table}: {sorted(missing)}')
        output_directory.mkdir()
        pending = output_directory / 'candidate.pending.db'
        archive = output_directory / 'source-evidence.db'
        with closing(sqlite3.connect(pending)) as target:
            template.backup(target)
        with closing(sqlite3.connect(archive)) as archive_connection:
            source.backup(archive_connection)
        table_evidence = {}
        with closing(sqlite3.connect(pending)) as target:
            # The source graph has cycles. Defer relational validation until all
            # tables in this NEW private candidate have been loaded atomically.
            target.execute('PRAGMA foreign_keys=OFF')
            target.execute('BEGIN')
            for table in business_tables:
                target.execute(f'DELETE FROM {_quoted(table)}')
            for table in business_tables:
                columns = target_shapes[table]
                rows = _rows(source, table, columns)
                placeholders = ','.join('?' for _ in columns)
                projection = ','.join(_quoted(column) for column in columns)
                target.executemany(
                    f'INSERT INTO {_quoted(table)} ({projection}) VALUES ({placeholders})', rows
                )
                expected_rows = _row_hashes(rows)
                if _row_hashes(_rows(target, table, columns)) != expected_rows:
                    raise ValueError(f'row preservation check failed: {table}')
                table_evidence[table] = {'rows': len(rows), 'columns': columns,
                                         'row_digest': hashlib.sha256(json.dumps(sorted(expected_rows.items())).encode()).hexdigest()}
            _assert_integrity(target)
            target.commit()
            target.execute('PRAGMA foreign_keys=ON')
            _assert_integrity(target)
            for table in SCHEMA_TABLES:
                columns = target_shapes.get(table)
                if columns and _row_hashes(_rows(target, table, columns)) != _row_hashes(_rows(template, table, columns)):
                    raise ValueError(f'schema checkpoint changed: {table}')
        with closing(_read_only(archive)) as archive_connection:
            _assert_integrity(archive_connection)
            for table, columns in source_shapes.items():
                if _row_hashes(_rows(source, table, columns)) != _row_hashes(_rows(archive_connection, table, columns)):
                    raise ValueError(f'original evidence copy mismatch: {table}')
        if _sha(source_path) != source_hash or _sha(template_path) != template_hash:
            raise ValueError('input files changed during candidate construction')
        receipt = {
            'status': 'PROJECTED_NOT_WORKFLOW_VERIFIED', 'workflow_verified': False,
            'created_at': datetime.now(timezone.utc).isoformat(),
            'source': str(source_path), 'source_sha256': source_hash,
            'schema_template': str(template_path), 'schema_template_sha256': template_hash,
            'trusted_schema_template_sha256': expected_template_sha256.lower(),
            'target_revision': TARGET_REVISION, 'source_evidence_sha256': _sha(archive),
            'excluded_tables': sorted(set(source_shapes) - set(target_shapes)),
            'excluded_columns': {table: sorted(set(source_shapes[table]) - set(columns))
                                 for table, columns in target_shapes.items()
                                 if table in source_shapes and set(source_shapes[table]) - set(columns)},
            'tables': table_evidence, 'sqlite_integrity': 'PASS', 'foreign_keys': 'PASS',
            'note': 'Newer-only values are preserved in source-evidence.db. No semantic migration or deploy approval is implied.',
        }
    pending.rename(output_directory / 'candidate.db')
    receipt['candidate_sha256'] = _sha(output_directory / 'candidate.db')
    with (output_directory / 'receipt.json').open('x', encoding='utf-8') as output:
        json.dump(receipt, output, ensure_ascii=False, indent=2)
    return receipt


def main() -> None:
    """Build a research candidate only when all immutable inputs are explicit."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source', type=Path, required=True)
    parser.add_argument('--schema-template', type=Path, required=True)
    parser.add_argument('--output-directory', type=Path, required=True)
    parser.add_argument('--source-sha256', required=True)
    parser.add_argument('--schema-template-sha256', required=True)
    args = parser.parse_args()
    result = build_candidate(args.source, args.schema_template, args.output_directory,
                             expected_source_sha256=args.source_sha256,
                             expected_template_sha256=args.schema_template_sha256)
    print(json.dumps({'status': result['status'], 'tables': len(result['tables']),
                      'excluded_tables': result['excluded_tables'],
                      'excluded_columns': result['excluded_columns'],
                      'output_directory': str(args.output_directory)}, ensure_ascii=False, indent=2))


if __name__ == '__main__':
    main()
