"""현행 DEXCOWIN MES 전체 스키마 정적 기준선."""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "20260715_0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


SQLITE_MES_CODE_SQL = (
    "model_symbol || '-' || process_type_code || '-' || "
    "printf('%04d', serial_no)"
)
PORTABLE_MES_CODE_SQL = (
    "model_symbol || '-' || process_type_code || '-' || "
    "CASE "
    "WHEN serial_no < 10 THEN '000' || CAST(serial_no AS VARCHAR) "
    "WHEN serial_no < 100 THEN '00' || CAST(serial_no AS VARCHAR) "
    "WHEN serial_no < 1000 THEN '0' || CAST(serial_no AS VARCHAR) "
    "ELSE CAST(serial_no AS VARCHAR) END"
)


def _mes_code_sql() -> str:
    """Preserve the SQLite contract without leaking printf into PostgreSQL DDL."""
    if op.get_context().dialect.name == "sqlite":
        return SQLITE_MES_CODE_SQL
    return PORTABLE_MES_CODE_SQL


def _model_pf_symbol_type() -> sa.TypeEngine:
    if op.get_context().dialect.name == "sqlite":
        return sa.Text()
    return sa.String(length=20)


def _model_pf_item_id_type() -> sa.TypeEngine:
    if op.get_context().dialect.name == "sqlite":
        return sa.CHAR(length=36)
    return sa.String(length=32)


def _model_pf_updated_at_type() -> sa.TypeEngine:
    if op.get_context().dialect.name == "sqlite":
        return sa.Text()
    return sa.DateTime()


def _upgrade_01() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_audit_logs',
    sa.Column('audit_id', sa.String(length=32), nullable=False),
    sa.Column('actor_pin_role', sa.String(length=32), nullable=False),
    sa.Column('actor_employee_code', sa.String(length=16), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('payload_summary', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index(op.f('ix_admin_audit_logs_action'), 'admin_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_actor_employee_code'), 'admin_audit_logs', ['actor_employee_code'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_created_at'), 'admin_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_request_id'), 'admin_audit_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_admin_audit_logs_target_type'), 'admin_audit_logs', ['target_type'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('color_hex', sa.String(length=7), nullable=True),
    sa.Column('io_enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('employees',
    sa.Column('employee_id', sa.String(length=32), nullable=False),
    sa.Column('employee_code', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('level', sa.Enum('ADMIN', 'MANAGER', 'STAFF', name='employee_level_enum'), nullable=False),
    sa.Column('warehouse_role', sa.String(length=20), server_default='none', nullable=False),
    sa.Column('department_role', sa.String(length=20), server_default='none', nullable=False),
    sa.Column('io_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('hidden_sidebar_tabs', sa.Text(), server_default='', nullable=False),
    sa.Column('login_notification_popup_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.String(length=5), nullable=False),
    sa.Column('pin_hash', sa.Text(), nullable=True),
    sa.Column('pin_last_changed', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('theme', sa.String(length=10), nullable=True),
    sa.CheckConstraint("department_role IN ('none', 'primary', 'deputy')", name='ck_employee_department_role'),
    sa.CheckConstraint("warehouse_role IN ('none', 'primary', 'deputy')", name='ck_employee_warehouse_role'),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_index(op.f('ix_employees_department'), 'employees', ['department'], unique=False)
    op.create_index(op.f('ix_employees_employee_code'), 'employees', ['employee_code'], unique=True)
    op.create_index(op.f('ix_employees_name'), 'employees', ['name'], unique=False)
    # ### end Alembic commands ###

def _upgrade_02() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process_types',
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.Column('prefix', sa.String(length=1), nullable=False),
    sa.Column('suffix', sa.String(length=1), nullable=False),
    sa.Column('stage_order', sa.SmallInteger(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('product_symbols',
    sa.Column('slot', sa.SmallInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=5), nullable=True),
    sa.Column('model_name', sa.String(length=50), nullable=True),
    sa.Column('is_finished_good', sa.Boolean(), nullable=False),
    sa.Column('is_reserved', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), server_default='0', nullable=False),
    sa.PrimaryKeyConstraint('slot')
    )
    op.create_index(op.f('ix_product_symbols_symbol'), 'product_symbols', ['symbol'], unique=True)
    op.create_table('system_settings',
    sa.Column('setting_key', sa.String(length=100), nullable=False),
    sa.Column('setting_value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('setting_key')
    )
    op.create_table('warehouse_angles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('angle_type', sa.String(length=20), server_default='angle', nullable=False),
    sa.Column('rows', sa.Integer(), nullable=False),
    sa.Column('layers', sa.Integer(), nullable=False),
    sa.Column('jaris_per_cell', sa.Integer(), nullable=False),
    sa.Column('pos_x', sa.Integer(), nullable=False),
    sa.Column('pos_y', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint("angle_type IN ('angle', 'aisle', 'pallet')", name='ck_wh_angle_type'),
    sa.CheckConstraint('jaris_per_cell >= 1', name='ck_wh_angle_jaris_pos'),
    sa.CheckConstraint('rows >= 1 AND layers >= 1', name='ck_wh_angle_dims_pos'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def _upgrade_03() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_special_zones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('zone_type', sa.String(length=20), nullable=False),
    sa.Column('pos_x', sa.Integer(), nullable=False),
    sa.Column('pos_y', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint("zone_type IN ('aisle', 'pallet')", name='ck_wh_zone_type'),
    sa.CheckConstraint('width >= 1 AND height >= 1', name='ck_wh_zone_size_pos'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_wh_zone_order', 'warehouse_special_zones', ['display_order', 'id'], unique=False)
    op.create_table('employee_assigned_models',
    sa.Column('employee_id', sa.String(length=32), nullable=False),
    sa.Column('slot', sa.SmallInteger(), nullable=False),
    sa.Column('priority', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot'], ['product_symbols.slot'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('employee_id', 'slot')
    )
    op.create_index('ix_eam_employee', 'employee_assigned_models', ['employee_id'], unique=False)
    op.create_index('ix_eam_employee_priority', 'employee_assigned_models', ['employee_id', 'priority'], unique=False)
    op.create_table('handovers',
    sa.Column('handover_id', sa.String(length=32), nullable=False),
    sa.Column('handover_code', sa.String(length=40), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'RECEIVED', name='handover_status_enum'), nullable=False),
    sa.Column('author_employee_id', sa.String(length=32), nullable=False),
    sa.Column('author_name', sa.String(length=100), nullable=False),
    sa.Column('from_department', sa.String(length=50), nullable=False),
    sa.Column('to_department', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('process_content', sa.Text(), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=True),
    sa.Column('doc_date', sa.DateTime(), nullable=True),
    sa.Column('analysis_text', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('received_by_employee_id', sa.String(length=32), nullable=True),
    sa.Column('received_by_name', sa.String(length=100), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['author_employee_id'], ['employees.employee_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['received_by_employee_id'], ['employees.employee_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('handover_id')
    )
    # ### end Alembic commands ###

def _upgrade_04() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_handovers_author_employee_id'), 'handovers', ['author_employee_id'], unique=False)
    op.create_index(op.f('ix_handovers_created_at'), 'handovers', ['created_at'], unique=False)
    op.create_index(op.f('ix_handovers_handover_code'), 'handovers', ['handover_code'], unique=True)
    op.create_index(op.f('ix_handovers_status'), 'handovers', ['status'], unique=False)
    op.create_table('io_batches',
    sa.Column('batch_id', sa.String(length=32), nullable=False),
    sa.Column('work_type', sa.String(length=32), nullable=False),
    sa.Column('sub_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('requester_employee_id', sa.String(length=32), nullable=False),
    sa.Column('requester_name', sa.String(length=100), nullable=False),
    sa.Column('requester_department', sa.String(length=50), nullable=False),
    sa.Column('from_department', sa.String(length=50), nullable=True),
    sa.Column('to_department', sa.String(length=50), nullable=True),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('stock_request_id', sa.String(length=32), nullable=True),
    sa.Column('reference_no', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('client_request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['requester_employee_id'], ['employees.employee_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_index(op.f('ix_io_batches_client_request_id'), 'io_batches', ['client_request_id'], unique=True)
    op.create_index(op.f('ix_io_batches_created_at'), 'io_batches', ['created_at'], unique=False)
    op.create_index(op.f('ix_io_batches_reference_no'), 'io_batches', ['reference_no'], unique=False)
    op.create_index(op.f('ix_io_batches_requester_employee_id'), 'io_batches', ['requester_employee_id'], unique=False)
    op.create_index('ix_io_batches_requester_status', 'io_batches', ['requester_employee_id', 'status'], unique=False)
    op.create_index(op.f('ix_io_batches_status'), 'io_batches', ['status'], unique=False)
    op.create_index(op.f('ix_io_batches_stock_request_id'), 'io_batches', ['stock_request_id'], unique=False)
    op.create_index(op.f('ix_io_batches_sub_type'), 'io_batches', ['sub_type'], unique=False)
    op.create_index(op.f('ix_io_batches_work_type'), 'io_batches', ['work_type'], unique=False)
    op.create_table('items',
    sa.Column('item_id', sa.String(length=32), nullable=False),
    sa.Column('item_name', sa.String(length=200), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('legacy_part', sa.String(length=50), nullable=True),
    sa.Column('legacy_item_type', sa.String(length=50), nullable=True),
    sa.Column('supplier', sa.String(length=200), nullable=True),
    sa.Column('min_stock', sa.Integer(), nullable=True),
    sa.Column('mes_code', sa.String(length=40), sa.Computed(_mes_code_sql(), persisted=True), nullable=True),
    sa.Column('model_symbol', sa.String(length=20), nullable=False),
    sa.Column('process_type_code', sa.String(length=2), nullable=False),
    sa.Column('serial_no', sa.Integer(), nullable=False),
    sa.Column('bom_completed_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('min_stock >= 0 OR min_stock IS NULL', name='ck_items_min_stock_nonneg'),
    sa.ForeignKeyConstraint(['process_type_code'], ['process_types.code'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    op.create_index(op.f('ix_items_legacy_part'), 'items', ['legacy_part'], unique=False)
    op.create_index(op.f('ix_items_mes_code'), 'items', ['mes_code'], unique=True)
    op.create_index(op.f('ix_items_model_symbol'), 'items', ['model_symbol'], unique=False)
    op.create_index(op.f('ix_items_process_type_code'), 'items', ['process_type_code'], unique=False)
    op.create_index(op.f('ix_items_sort_order'), 'items', ['sort_order'], unique=False)
    # ### end Alembic commands ###

def _upgrade_05() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse_boxes',
    sa.Column('box_id', sa.String(length=32), nullable=False),
    sa.Column('angle_id', sa.Integer(), nullable=False),
    sa.Column('row_no', sa.Integer(), nullable=False),
    sa.Column('layer_no', sa.Integer(), nullable=False),
    sa.Column('jari_index', sa.Integer(), nullable=False),
    sa.Column('size', sa.Enum('LARGE', 'MEDIUM', 'SMALL', name='box_size_enum'), nullable=False),
    sa.Column('stack_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint('jari_index >= 0', name='ck_wh_box_jari_nonneg'),
    sa.CheckConstraint('row_no >= 1 AND layer_no >= 1', name='ck_wh_box_coord_pos'),
    sa.ForeignKeyConstraint(['angle_id'], ['warehouse_angles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('box_id')
    )
    op.create_index(op.f('ix_warehouse_boxes_angle_id'), 'warehouse_boxes', ['angle_id'], unique=False)
    op.create_index('ix_wh_box_coord', 'warehouse_boxes', ['angle_id', 'row_no', 'layer_no', 'jari_index'], unique=False)
    op.create_table('warehouse_special_zone_audits',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('actor_employee_id', sa.String(length=32), nullable=True),
    sa.Column('actor_employee_code', sa.String(length=30), nullable=True),
    sa.Column('actor_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['actor_employee_id'], ['employees.employee_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['zone_id'], ['warehouse_special_zones.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_special_zone_audits_actor_employee_id'), 'warehouse_special_zone_audits', ['actor_employee_id'], unique=False)
    op.create_index(op.f('ix_warehouse_special_zone_audits_zone_id'), 'warehouse_special_zone_audits', ['zone_id'], unique=False)
    op.create_table('bom',
    sa.Column('bom_id', sa.String(length=32), nullable=False),
    sa.Column('parent_item_id', sa.String(length=32), nullable=False),
    sa.Column('child_item_id', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['child_item_id'], ['items.item_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_item_id'], ['items.item_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bom_id'),
    sa.UniqueConstraint('parent_item_id', 'child_item_id', name='uq_bom_parent_child')
    )
    # ### end Alembic commands ###

def _upgrade_06() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_bom_child', 'bom', ['child_item_id'], unique=False)
    op.create_index(op.f('ix_bom_child_item_id'), 'bom', ['child_item_id'], unique=False)
    op.create_index('ix_bom_parent', 'bom', ['parent_item_id'], unique=False)
    op.create_index(op.f('ix_bom_parent_item_id'), 'bom', ['parent_item_id'], unique=False)
    op.create_table('employee_item_orders',
    sa.Column('employee_id', sa.String(length=32), nullable=False),
    sa.Column('item_id', sa.String(length=32), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('employee_id', 'item_id')
    )
    op.create_index('ix_employee_item_orders_employee', 'employee_item_orders', ['employee_id'], unique=False)
    op.create_table('handover_lines',
    sa.Column('line_id', sa.String(length=32), nullable=False),
    sa.Column('handover_id', sa.String(length=32), nullable=False),
    sa.Column('item_id', sa.String(length=32), nullable=False),
    sa.Column('item_name_snapshot', sa.String(length=200), nullable=False),
    sa.Column('mes_code_snapshot', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_handover_line_qty_pos'),
    sa.ForeignKeyConstraint(['handover_id'], ['handovers.handover_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('line_id')
    )
    op.create_index(op.f('ix_handover_lines_handover_id'), 'handover_lines', ['handover_id'], unique=False)
    op.create_index(op.f('ix_handover_lines_item_id'), 'handover_lines', ['item_id'], unique=False)
    # ### end Alembic commands ###

def _upgrade_07() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('inventory_id', sa.String(length=32), nullable=False),
    sa.Column('item_id', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('warehouse_qty', sa.Integer(), nullable=False),
    sa.Column('pending_quantity', sa.Integer(), nullable=False),
    sa.Column('last_reserver_employee_id', sa.String(length=32), nullable=True),
    sa.Column('last_reserver_name', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint('pending_quantity >= 0', name='ck_inventory_pending_nonneg'),
    sa.CheckConstraint('quantity >= 0', name='ck_inventory_quantity_nonneg'),
    sa.CheckConstraint('warehouse_qty >= 0', name='ck_inventory_warehouse_nonneg'),
    sa.CheckConstraint('warehouse_qty >= pending_quantity', name='ck_inventory_pending_le_warehouse'),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['last_reserver_employee_id'], ['employees.employee_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('inventory_id')
    )
    op.create_index(op.f('ix_inventory_item_id'), 'inventory', ['item_id'], unique=True)
    op.create_table('inventory_locations',
    sa.Column('location_id', sa.String(length=32), nullable=False),
    sa.Column('item_id', sa.String(length=32), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PRODUCTION', 'DEFECTIVE', name='location_status_enum'), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('defective_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('quantity >= 0', name='ck_invloc_quantity_nonneg'),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('location_id'),
    sa.UniqueConstraint('item_id', 'department', 'status', name='uq_invloc_item_dept_status')
    )
    op.create_index(op.f('ix_inventory_locations_defective_at'), 'inventory_locations', ['defective_at'], unique=False)
    op.create_index(op.f('ix_inventory_locations_department'), 'inventory_locations', ['department'], unique=False)
    op.create_index(op.f('ix_inventory_locations_item_id'), 'inventory_locations', ['item_id'], unique=False)
    op.create_index(op.f('ix_inventory_locations_status'), 'inventory_locations', ['status'], unique=False)
    op.create_index('ix_invloc_dept', 'inventory_locations', ['department'], unique=False)
    op.create_index('ix_invloc_item', 'inventory_locations', ['item_id'], unique=False)
    op.create_table('io_bundles',
    sa.Column('bundle_id', sa.String(length=32), nullable=False),
    sa.Column('batch_id', sa.String(length=32), nullable=False),
    sa.Column('source_kind', sa.String(length=24), nullable=False),
    sa.Column('source_item_id', sa.String(length=32), nullable=True),
    sa.Column('title_snapshot', sa.String(length=220), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('expanded_level', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['io_batches.batch_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_item_id'], ['items.item_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('bundle_id')
    )
    # ### end Alembic commands ###

def _upgrade_08() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_io_bundles_batch_id'), 'io_bundles', ['batch_id'], unique=False)
    op.create_index(op.f('ix_io_bundles_source_item_id'), 'io_bundles', ['source_item_id'], unique=False)
    op.create_table('model_pf_pins',
    sa.Column('model_symbol', _model_pf_symbol_type(), nullable=False),
    sa.Column('pf_item_id', _model_pf_item_id_type(), nullable=False),
    sa.Column('updated_at', _model_pf_updated_at_type(), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['pf_item_id'], ['items.item_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('model_symbol')
    )
    op.create_table('shipping_requests',
    sa.Column('request_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('REQUESTED', 'PREPARING', 'PREPARED', 'PICKED_UP', name='shipping_request_status_enum'), server_default='REQUESTED', nullable=False),
    sa.Column('base_pf_item_id', sa.String(length=32), nullable=False),
    sa.Column('final_pa_item_id', sa.String(length=32), nullable=True),
    sa.Column('final_pf_item_id', sa.String(length=32), nullable=True),
    sa.Column('request_quantity', sa.Integer(), server_default='1', nullable=False),
    sa.Column('requested_by_name', sa.String(length=100), nullable=True),
    sa.Column('custom_pa_name', sa.String(length=200), nullable=True),
    sa.Column('custom_pf_name', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('prepared_at', sa.DateTime(), nullable=True),
    sa.Column('picked_up_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['base_pf_item_id'], ['items.item_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['final_pa_item_id'], ['items.item_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['final_pf_item_id'], ['items.item_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_index(op.f('ix_shipping_requests_base_pf_item_id'), 'shipping_requests', ['base_pf_item_id'], unique=False)
    op.create_index(op.f('ix_shipping_requests_created_at'), 'shipping_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_shipping_requests_final_pa_item_id'), 'shipping_requests', ['final_pa_item_id'], unique=False)
    op.create_index(op.f('ix_shipping_requests_final_pf_item_id'), 'shipping_requests', ['final_pf_item_id'], unique=False)
    op.create_index(op.f('ix_shipping_requests_picked_up_at'), 'shipping_requests', ['picked_up_at'], unique=False)
    op.create_index(op.f('ix_shipping_requests_prepared_at'), 'shipping_requests', ['prepared_at'], unique=False)
    op.create_index(op.f('ix_shipping_requests_status'), 'shipping_requests', ['status'], unique=False)
    op.create_table('stock_requests',
    sa.Column('request_id', sa.String(length=32), nullable=False),
    sa.Column('request_code', sa.String(length=40), nullable=True),
    sa.Column('client_request_id', sa.String(length=64), nullable=True),
    sa.Column('requester_employee_id', sa.String(length=32), nullable=False),
    sa.Column('requester_name', sa.String(length=100), nullable=False),
    sa.Column('requester_department', sa.String(length=50), nullable=False),
    sa.Column('request_type', sa.Enum('RAW_RECEIVE', 'RAW_SHIP', 'WAREHOUSE_TO_DEPT', 'DEPT_TO_WAREHOUSE', 'DEPT_INTERNAL', 'MARK_DEFECTIVE_WH', 'MARK_DEFECTIVE_PROD', 'SUPPLIER_RETURN', 'PACKAGE_OUT', 'INTERNAL_USE', 'MANUAL_ADJUSTMENT', 'DEFECT_SCRAP', 'DEFECT_RETURN', 'DEFECT_DISASSEMBLE', 'SCRAP_NORMAL', 'RETURN_NORMAL', 'REWORK_NORMAL', name='stock_request_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'RESERVED', 'REJECTED', 'CANCELLED', 'COMPLETED', 'FAILED_APPROVAL', name='stock_request_status_enum'), nullable=False),
    sa.Column('requires_warehouse_approval', sa.Boolean(), nullable=False),
    sa.Column('reserved_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by_employee_id', sa.String(length=32), nullable=True),
    sa.Column('approved_by_name', sa.String(length=100), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_by_employee_id', sa.String(length=32), nullable=True),
    sa.Column('rejected_by_name', sa.String(length=100), nullable=True),
    sa.Column('rejected_at', sa.DateTime(), nullable=True),
    sa.Column('rejected_reason', sa.Text(), nullable=True),
    sa.Column('requires_department_approval', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('department_approved_by_employee_id', sa.String(length=32), nullable=True),
    sa.Column('department_approved_by_name', sa.String(length=100), nullable=True),
    sa.Column('department_approved_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('reference_no', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reason_category', sa.String(length=50), nullable=True),
    sa.Column('reason_memo', sa.Text(), nullable=True),
    sa.Column('operation_batch_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_employee_id'], ['employees.employee_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_approved_by_employee_id'], ['employees.employee_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['operation_batch_id'], ['io_batches.batch_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rejected_by_employee_id'], ['employees.employee_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['requester_employee_id'], ['employees.employee_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('request_id')
    )
    # ### end Alembic commands ###

def _upgrade_09() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_stock_requests_client_request_id'), 'stock_requests', ['client_request_id'], unique=True)
    op.create_index(op.f('ix_stock_requests_created_at'), 'stock_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_stock_requests_operation_batch_id'), 'stock_requests', ['operation_batch_id'], unique=False)
    op.create_index(op.f('ix_stock_requests_request_code'), 'stock_requests', ['request_code'], unique=True)
    op.create_index(op.f('ix_stock_requests_request_type'), 'stock_requests', ['request_type'], unique=False)
    op.create_index(op.f('ix_stock_requests_requester_employee_id'), 'stock_requests', ['requester_employee_id'], unique=False)
    op.create_index(op.f('ix_stock_requests_status'), 'stock_requests', ['status'], unique=False)
    op.create_table('warehouse_box_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('box_id', sa.String(length=32), nullable=False),
    sa.Column('item_id', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_wh_boxitem_qty_nonneg'),
    sa.ForeignKeyConstraint(['box_id'], ['warehouse_boxes.box_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_box_items_box_id'), 'warehouse_box_items', ['box_id'], unique=False)
    op.create_index(op.f('ix_warehouse_box_items_item_id'), 'warehouse_box_items', ['item_id'], unique=False)
    op.create_index('ix_wh_boxitem_item', 'warehouse_box_items', ['item_id'], unique=False)
    op.create_table('warehouse_special_zone_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_wh_zoneitem_qty_nonneg'),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['zone_id'], ['warehouse_special_zones.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_special_zone_items_item_id'), 'warehouse_special_zone_items', ['item_id'], unique=False)
    op.create_index(op.f('ix_warehouse_special_zone_items_zone_id'), 'warehouse_special_zone_items', ['zone_id'], unique=False)
    op.create_index('ix_wh_zoneitem_item', 'warehouse_special_zone_items', ['item_id'], unique=False)
    # ### end Alembic commands ###

def _upgrade_10() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('io_lines',
    sa.Column('line_id', sa.String(length=32), nullable=False),
    sa.Column('bundle_id', sa.String(length=32), nullable=False),
    sa.Column('item_id', sa.String(length=32), nullable=False),
    sa.Column('item_name_snapshot', sa.String(length=200), nullable=False),
    sa.Column('mes_code_snapshot', sa.String(length=50), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=False),
    sa.Column('from_bucket', sa.String(length=20), nullable=False),
    sa.Column('from_department', sa.String(length=50), nullable=True),
    sa.Column('to_bucket', sa.String(length=20), nullable=False),
    sa.Column('to_department', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('bom_expected', sa.Integer(), nullable=True),
    sa.Column('included', sa.Boolean(), nullable=False),
    sa.Column('origin', sa.String(length=24), nullable=False),
    sa.Column('edited', sa.Boolean(), nullable=False),
    sa.Column('has_children_snapshot', sa.Boolean(), nullable=False),
    sa.Column('shortage', sa.Integer(), nullable=False),
    sa.Column('exclusion_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint('quantity >= 0', name='ck_io_line_qty_nonneg'),
    sa.ForeignKeyConstraint(['bundle_id'], ['io_bundles.bundle_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('line_id')
    )
    op.create_index('ix_io_line_item_included', 'io_lines', ['item_id', 'included'], unique=False)
    op.create_index(op.f('ix_io_lines_bundle_id'), 'io_lines', ['bundle_id'], unique=False)
    op.create_index(op.f('ix_io_lines_item_id'), 'io_lines', ['item_id'], unique=False)
    op.create_table('notifications',
    sa.Column('notification_id', sa.String(length=32), nullable=False),
    sa.Column('recipient_employee_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('target_tab', sa.String(length=32), nullable=True),
    sa.Column('target_section', sa.String(length=32), nullable=True),
    sa.Column('related_request_id', sa.String(length=32), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_employee_id'], ['employees.employee_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_request_id'], ['stock_requests.request_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index('ix_notification_recipient_unread', 'notifications', ['recipient_employee_id', 'is_read'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_employee_id'), 'notifications', ['recipient_employee_id'], unique=False)
    op.create_index(op.f('ix_notifications_related_request_id'), 'notifications', ['related_request_id'], unique=False)
    op.create_table('shipping_allocations',
    sa.Column('allocation_id', sa.String(length=32), nullable=False),
    sa.Column('request_id', sa.String(length=32), nullable=False),
    sa.Column('item_id', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='RESERVED', nullable=False),
    sa.Column('reference_no', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('released_at', sa.DateTime(), nullable=True),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('released_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['request_id'], ['shipping_requests.request_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('allocation_id')
    )
    # ### end Alembic commands ###

def _upgrade_11() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_shipping_alloc_item_status', 'shipping_allocations', ['item_id', 'status'], unique=False)
    op.create_index('ix_shipping_alloc_req_status', 'shipping_allocations', ['request_id', 'status'], unique=False)
    op.create_index(op.f('ix_shipping_allocations_created_at'), 'shipping_allocations', ['created_at'], unique=False)
    op.create_index(op.f('ix_shipping_allocations_item_id'), 'shipping_allocations', ['item_id'], unique=False)
    op.create_index(op.f('ix_shipping_allocations_reference_no'), 'shipping_allocations', ['reference_no'], unique=False)
    op.create_index(op.f('ix_shipping_allocations_request_id'), 'shipping_allocations', ['request_id'], unique=False)
    op.create_index(op.f('ix_shipping_allocations_status'), 'shipping_allocations', ['status'], unique=False)
    op.create_table('shipping_request_bom_lines',
    sa.Column('line_id', sa.String(length=32), nullable=False),
    sa.Column('request_id', sa.String(length=32), nullable=False),
    sa.Column('parent_stage', sa.String(length=2), nullable=False),
    sa.Column('child_item_id', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('included', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('origin', sa.String(length=20), server_default='CUSTOM', nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['child_item_id'], ['items.item_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['request_id'], ['shipping_requests.request_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('line_id'),
    sa.UniqueConstraint('request_id', 'parent_stage', 'child_item_id', name='uq_shipping_bom_line')
    )
    op.create_index('ix_shipping_bom_req_stage', 'shipping_request_bom_lines', ['request_id', 'parent_stage'], unique=False)
    op.create_index(op.f('ix_shipping_request_bom_lines_child_item_id'), 'shipping_request_bom_lines', ['child_item_id'], unique=False)
    op.create_index(op.f('ix_shipping_request_bom_lines_parent_stage'), 'shipping_request_bom_lines', ['parent_stage'], unique=False)
    op.create_index(op.f('ix_shipping_request_bom_lines_request_id'), 'shipping_request_bom_lines', ['request_id'], unique=False)
    op.create_table('shipping_request_checklist_lines',
    sa.Column('line_id', sa.String(length=32), nullable=False),
    sa.Column('request_id', sa.String(length=32), nullable=False),
    sa.Column('item_id', sa.String(length=32), nullable=False),
    sa.Column('label_snapshot', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('checked', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['request_id'], ['shipping_requests.request_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('line_id'),
    sa.UniqueConstraint('request_id', 'item_id', name='uq_shipping_checklist_item')
    )
    op.create_index(op.f('ix_shipping_request_checklist_lines_item_id'), 'shipping_request_checklist_lines', ['item_id'], unique=False)
    op.create_index(op.f('ix_shipping_request_checklist_lines_request_id'), 'shipping_request_checklist_lines', ['request_id'], unique=False)
    # ### end Alembic commands ###

def _upgrade_12() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipping_request_companion_lines',
    sa.Column('line_id', sa.String(length=32), nullable=False),
    sa.Column('request_id', sa.String(length=32), nullable=False),
    sa.Column('item_id', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['request_id'], ['shipping_requests.request_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('line_id')
    )
    op.create_index(op.f('ix_shipping_request_companion_lines_item_id'), 'shipping_request_companion_lines', ['item_id'], unique=False)
    op.create_index(op.f('ix_shipping_request_companion_lines_request_id'), 'shipping_request_companion_lines', ['request_id'], unique=False)
    op.create_table('shipping_request_events',
    sa.Column('event_id', sa.String(length=32), nullable=False),
    sa.Column('request_id', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['shipping_requests.request_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_shipping_request_events_created_at'), 'shipping_request_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_shipping_request_events_event_type'), 'shipping_request_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_shipping_request_events_request_id'), 'shipping_request_events', ['request_id'], unique=False)
    op.create_table('transaction_logs',
    sa.Column('log_id', sa.String(length=32), nullable=False),
    sa.Column('item_id', sa.String(length=32), nullable=False),
    sa.Column('transaction_type', sa.Enum('RECEIVE', 'PRODUCE', 'SHIP', 'ADJUST', 'BACKFLUSH', 'DISASSEMBLE', 'TRANSFER_TO_PROD', 'TRANSFER_TO_WH', 'TRANSFER_DEPT', 'MARK_DEFECTIVE', 'UNMARK_DEFECTIVE', 'DEFECT_SCRAP', 'SUPPLIER_RETURN', 'INTERNAL_USE', name='transaction_type_enum'), nullable=False),
    sa.Column('quantity_change', sa.Integer(), nullable=False),
    sa.Column('quantity_before', sa.Integer(), nullable=True),
    sa.Column('quantity_after', sa.Integer(), nullable=True),
    sa.Column('warehouse_qty_before', sa.Integer(), nullable=True),
    sa.Column('warehouse_qty_after', sa.Integer(), nullable=True),
    sa.Column('transfer_qty', sa.Integer(), nullable=True),
    sa.Column('reference_no', sa.String(length=100), nullable=True),
    sa.Column('produced_by', sa.String(length=100), nullable=True),
    sa.Column('producer_employee_id', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reason_category', sa.String(length=32), nullable=True),
    sa.Column('reason_memo', sa.Text(), nullable=True),
    sa.Column('client_request_id', sa.String(length=36), nullable=True),
    sa.Column('operation_batch_id', sa.String(length=32), nullable=True),
    sa.Column('shipping_request_id', sa.String(length=32), nullable=True),
    sa.Column('shipping_phase', sa.String(length=20), nullable=True),
    sa.Column('department', sa.String(length=50), nullable=True),
    sa.Column('cancelled', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('cancel_reason', sa.Text(), nullable=True),
    sa.Column('cancelled_by', sa.String(length=32), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('inventory_effect', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cancelled_by'], ['employees.employee_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['operation_batch_id'], ['io_batches.batch_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['producer_employee_id'], ['employees.employee_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['shipping_request_id'], ['shipping_requests.request_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id'),
    sa.UniqueConstraint('client_request_id')
    )
    # ### end Alembic commands ###

def _upgrade_13() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_transaction_logs_archived_at'), 'transaction_logs', ['archived_at'], unique=False)
    op.create_index(op.f('ix_transaction_logs_created_at'), 'transaction_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_transaction_logs_department'), 'transaction_logs', ['department'], unique=False)
    op.create_index(op.f('ix_transaction_logs_item_id'), 'transaction_logs', ['item_id'], unique=False)
    op.create_index(op.f('ix_transaction_logs_operation_batch_id'), 'transaction_logs', ['operation_batch_id'], unique=False)
    op.create_index(op.f('ix_transaction_logs_producer_employee_id'), 'transaction_logs', ['producer_employee_id'], unique=False)
    op.create_index(op.f('ix_transaction_logs_reason_category'), 'transaction_logs', ['reason_category'], unique=False)
    op.create_index(op.f('ix_transaction_logs_reference_no'), 'transaction_logs', ['reference_no'], unique=False)
    op.create_index(op.f('ix_transaction_logs_shipping_phase'), 'transaction_logs', ['shipping_phase'], unique=False)
    op.create_index(op.f('ix_transaction_logs_shipping_request_id'), 'transaction_logs', ['shipping_request_id'], unique=False)
    op.create_index(op.f('ix_transaction_logs_transaction_type'), 'transaction_logs', ['transaction_type'], unique=False)
    op.create_index('ix_tx_batch_created', 'transaction_logs', ['operation_batch_id', 'created_at'], unique=False)
    op.create_index('ix_tx_item_created', 'transaction_logs', ['item_id', 'created_at'], unique=False)
    op.create_index('ix_tx_shipping_request', 'transaction_logs', ['shipping_request_id', 'created_at'], unique=False)
    op.create_index('ix_tx_type_created', 'transaction_logs', ['transaction_type', 'created_at'], unique=False)
    op.create_table('stock_request_lines',
    sa.Column('line_id', sa.String(length=32), nullable=False),
    sa.Column('request_id', sa.String(length=32), nullable=False),
    sa.Column('item_id', sa.String(length=32), nullable=False),
    sa.Column('item_name_snapshot', sa.String(length=200), nullable=False),
    sa.Column('mes_code_snapshot', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('from_bucket', sa.Enum('WAREHOUSE', 'PRODUCTION', 'DEFECTIVE', 'NONE', name='request_bucket_enum'), nullable=False),
    sa.Column('from_department', sa.String(length=50), nullable=True),
    sa.Column('to_bucket', sa.Enum('WAREHOUSE', 'PRODUCTION', 'DEFECTIVE', 'NONE', name='request_bucket_enum'), nullable=False),
    sa.Column('to_department', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'RESERVED', 'REJECTED', 'CANCELLED', 'COMPLETED', 'FAILED_APPROVAL', name='stock_request_status_enum'), nullable=False),
    sa.Column('operation_line_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.CheckConstraint('quantity > 0', name='ck_stock_request_line_qty_positive'),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operation_line_id'], ['io_lines.line_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['stock_requests.request_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('line_id')
    )
    op.create_index('ix_stock_request_line_item_status', 'stock_request_lines', ['item_id', 'status'], unique=False)
    op.create_index(op.f('ix_stock_request_lines_item_id'), 'stock_request_lines', ['item_id'], unique=False)
    op.create_index(op.f('ix_stock_request_lines_operation_line_id'), 'stock_request_lines', ['operation_line_id'], unique=False)
    op.create_index(op.f('ix_stock_request_lines_request_id'), 'stock_request_lines', ['request_id'], unique=False)
    op.create_table('transaction_edit_logs',
    sa.Column('edit_id', sa.String(length=32), nullable=False),
    sa.Column('original_log_id', sa.String(length=32), nullable=False),
    sa.Column('edited_by_employee_id', sa.String(length=32), nullable=False),
    sa.Column('edited_by_name', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('before_payload', sa.Text(), nullable=False),
    sa.Column('after_payload', sa.Text(), nullable=False),
    sa.Column('correction_log_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['correction_log_id'], ['transaction_logs.log_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['edited_by_employee_id'], ['employees.employee_id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['original_log_id'], ['transaction_logs.log_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('edit_id')
    )
    op.create_index(op.f('ix_transaction_edit_logs_original_log_id'), 'transaction_edit_logs', ['original_log_id'], unique=False)
    # ### end Alembic commands ###

def upgrade() -> None:
    _upgrade_01()
    _upgrade_02()
    _upgrade_03()
    _upgrade_04()
    _upgrade_05()
    _upgrade_06()
    _upgrade_07()
    _upgrade_08()
    _upgrade_09()
    _upgrade_10()
    _upgrade_11()
    _upgrade_12()
    _upgrade_13()


def downgrade() -> None:
    raise RuntimeError(
        "baseline downgrade is disabled to protect all application data"
    )
